services:
    mysql:
      image: mysql:8.4.5
      command: --mysql-native-password=ON
      environment:
        MYSQL_DATABASE: ${MYSQL_DB}
        MYSQL_USER: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - ${MYSQL_PORT}:3306
      volumes:
        - 'mysqldata:/var/lib/mysql'
volumes:
  mysqldata:


